### ISSUE TITLE
Issue with Domoticz.Configuration in Beta Versions

### ISSUE THREAD

**Issue by Xenomes** [domoticz/domoticz#6343]
Hi Developers,

Has there been a change in the behavior of Domoticz.Configuration in the Beta version?

I use Domoticz.Configuration to store information about devices in Domoticz at the time of their creation. However, since the first Beta release after the stable 2025.1 version, I’ve been encountering the following error when attempting to write a dictionary to Domoticz.Configuration:

```
Error: (JSONtoPython) failed to add item '-1', to list for string.
Error: Tuya Cloud: Domoticz.Configuration operation failed: <built-in function Configuration> returned a result with an exception set
```

The data is stored once at the start of the plugin and read back on every heartbeat. I also added a routine to purge the Domoticz.Configuration, but that hasn’t resolved all the error messages.

I’m using the subroutine provided under "Developing a Python plugin."

Thanks in advance for any insights or suggestions.

Best regards,
Xenomes

**Comment by waltervl** [comment]
Seems nothing has changed in plugin framework in beta (first release 5th of May) https://github.com/domoticz/domoticz/tree/development/hardware/plugins.

Perhaps it has something to do with Python in newer OS's handling things differently? What Python version are you using?

**Comment by Xenomes** [comment]
Hi Walter,

Thank you for your response. I am using the official Docker container to ensure compatibility with the user environment, so Python 3.11 is the version in use.

To isolate the issue, I created a clean test version here:
https://github.com/Xenomes/Test

The test simply pushes ["off","cold","hot","wind"] to Domoticz and reads it back. Here’s what I observed:

Sending "off" works correctly.
Sending ["off","cold","hot","wind"] results in the error.

After the error occurs, sending further commands does not resolve it, the only way to fix is to delete and recreate the plugin.

Let me know if you need additional details to investigate further.

Best regards,
Xenomes

**Comment by Xenomes** [comment]
I just installed the Domoticz stable version on Bookworm, and the same error persists. This confirms the issue isn't specific to the Beta. it's related to Python 3.11.2 compatibility within Domoticz's code.

**Comment by waltervl** [comment]
@dnpwwo Any idea what is going on here?

**Comment by pipiche38** [comment]
@waltervl I'll have a look to the test plugin, In the https://github.com/zigbeefordomoticz/Domoticz-Zigbee plugin we have the possibility to store the all Plugin database and I do not have issue with the latest Domoticz version Version: 2025.1 (build 16672).

**Comment by pipiche38** [comment]
No issue found with Docker image and Python Version: 3.9.2

Will build a domoticz image with python3.11

> domoticz    | 2025-06-02 11:32:12.419  Test : 'DomoticzVersion':'2025.1 (build 16672)'
> domoticz    | 2025-06-02 11:32:12.419  Test : 'DomoticzHash':'7f861f5bd'
> domoticz    | 2025-06-02 11:32:12.419  Test : 'DomoticzBuildTime':'2025-05-05 08:31:45'
> domoticz    | 2025-06-02 11:32:12.419  Test : Device count: 1
> domoticz    | 2025-06-02 11:32:12.419  Test : Device ID:       '123'
> domoticz    | 2025-06-02 11:32:12.419  Test : --->Unit Count:      '1'
> domoticz    | 2025-06-02 11:32:12.419  Test : --->Unit:           1
> domoticz    | 2025-06-02 11:32:12.419  Test : --->Unit Name:     'Test switch'
> domoticz    | 2025-06-02 11:32:12.419  Test : --->Unit nValue:    0
> domoticz    | 2025-06-02 11:32:12.419  Test : --->Unit sValue:   ''
> domoticz    | 2025-06-02 11:32:12.419  Test : --->Unit LastLevel: 0
> domoticz    | 2025-06-02 11:32:12.419  Test : Pushing 'PollIntervalDirective' on to queue
> domoticz    | 2025-06-02 11:32:12.419  Test : Acquiring GIL for 'onStartCallback'
> domoticz    | 2025-06-02 11:32:12.419  Test : Processing 'PollIntervalDirective' message
> domoticz    | 2025-06-02 11:32:12.419  Test : Acquiring GIL for 'PollIntervalDirective'
> domoticz    | 2025-06-02 11:32:12.419  Test : Heartbeat interval set to: 30.
> domoticz    | 2025-06-02 11:32:12.419  Test : Acquiring GIL for 'PollIntervalDirective'
> domoticz    | 2025-06-02 11:32:16.180  Motherboard: Temp (Internal Temperature)
> domoticz    | 2025-06-02 11:32:16.181  Motherboard: General/Percentage (CPU_Usage)
> domoticz    | 2025-06-02 11:32:42.003  Test : Pushing 'onHeartbeatCallback' on to queue
> domoticz    | 2025-06-02 11:32:42.053  Test : Processing 'onHeartbeatCallback' message
> domoticz    | 2025-06-02 11:32:42.053  Test : Acquiring GIL for 'onHeartbeatCallback'
> domoticz    | 2025-06-02 11:32:42.053  Test : Calling message handler 'onHeartbeat' on 'module' type object.
> domoticz    | 2025-06-02 11:32:42.053  Test : onHeartbeat called
> domoticz    | 2025-06-02 11:32:42.054  Test : {'123': ['off', 'cold', 'hot', 'wind']}
> domoticz    | 2025-06-02 11:32:42.054  Test : Acquiring GIL for 'onHeartbeatCallback'
> domoticz    | 2025-06-02 11:32:46.184  Motherboard: General/Percentage (CPU_Usage)
> domoticz    | 2025-06-02 11:32:46.184  Motherboard: General/Percentage (Memory Usage)
> domoticz    | 2025-06-02 11:32:46.185  Motherboard: General/Custom Sensor (Process Usage)
> domoticz    | 2025-06-02 11:33:12.037  Test : Pushing 'onHeartbeatCallback' on to queue
> domoticz    | 2025-06-02 11:33:12.087  Test : Processing 'onHeartbeatCallback' message
> domoticz    | 2025-06-02 11:33:12.087  Test : Acquiring GIL for 'onHeartbeatCallback'
> domoticz    | 2025-06-02 11:33:12.087  Test : Calling message handler 'onHeartbeat' on 'module' type object.
> domoticz    | 2025-06-02 11:33:12.087  Test : onHeartbeat called
> domoticz    | 2025-06-02 11:33:12.088  Test : {'123': ['off', 'cold', 'hot', 'wind']}
> domoticz    | 2025-06-02 11:33:12.088  Test : Acquiring GIL for 'onHeartbeatCallback'
> domoticz    | 2025-06-02 11:33:16.188  Motherboard: General/Percentage (CPU_Usage)
> domoticz    | 2025-06-02 11:33:26.191  Motherboard: Temp (Internal Temperature)
> domoticz    | 2025-06-02 11:33:42.021  Test : Pushing 'onHeartbeatCallback' on to queue
> domoticz    | 2025-06-02 11:33:42.071  Test : Processing 'onHeartbeatCallback' message
> domoticz    | 2025-06-02 11:33:42.071  Test : Acquiring GIL for 'onHeartbeatCallback'
> domoticz    | 2025-06-02 11:33:42.071  Test : Calling message handler 'onHeartbeat' on 'module' type object.
> domoticz    | 2025-06-02 11:33:42.071  Test : onHeartbeat called
> domoticz    | 2025-06-02 11:33:42.072  Test : {'123': ['off', 'cold', 'hot', 'wind']}
> domoticz    | 2025-06-02 11:33:42.072  Test : Acquiring GIL for 'onHeartbeatCallback'
> domoticz    | 2025-06-02 11:33:46.193  Motherboard: General/Percentage (CPU_Usage)

**Comment by Xenomes** [comment]
> No issue found with Docker image and Python Version: 3.9.2
> 
> Will build a domoticz image with python3.11
> 
> > domoticz    | 2025-06-02 11:32:12.419  Test : 'DomoticzVersion':'2025.1 (build 16672)'
> > domoticz    | 2025-06-02 11:32:12.419  Test : 'DomoticzHash':'7f861f5bd'
> > domoticz    | 2025-06-02 11:32:12.419  Test : 'DomoticzBuildTime':'2025-05-05 08:31:45'

Hi pipiche38,

Thanks for looking in to the issue, I will look in to the plugin to how the data is stored.
I see the version 16672 in the log, this one is before the stable versions 2025.1 (16678) was his on Bullseye of Bookworm?

Did you test the Beta version (16712) on Bookworm (Docker)?

**Comment by pipiche38** [comment]
Looks very strange and would required further investigation.

https://github.com/domoticz/domoticz/blob/fd9e1018c944a125c4445d02fdde38108376e7f2/hardware/plugins/PluginProtocols.cpp#L212

seems to make the trick

```
PyBorrowedRef pObj = Py_BuildValue("s", sString.c_str(), sString.length());
```

instead of 

```
PyBorrowedRef pObj = Py_BuildValue("s#", sString.c_str());
```

**Comment by pipiche38** [comment]
new step is to understand why we had 's#'

**Comment by gizmocuz** [comment]
Maybe we need to declare PY_SSIZE_T_CLEAN ?

Note On Python 3.12 and older, the macro PY_SSIZE_T_CLEAN must be defined before including Python.h to use all # variants of formats (s#, y#, etc.) explained below. This is not necessary on Python 3.13 and later.

But if it works without the hashtag... It's the only location using it

**Comment by pipiche38** [comment]
yes it is the only location, and my understanding between 's' and 's#' is that on 's' we are expecting a NULL terminated string as 'soon as for 's#' we are providing the length, but also **the result is stored into two C variables** 


> s# ([str](https://docs.python.org/3/library/stdtypes.html#str), read-only [bytes-like object](https://docs.python.org/3/glossary.html#term-bytes-like-object)) [const char *, [Py_ssize_t](https://docs.python.org/3/c-api/intro.html#c.Py_ssize_t)]

    Like s*, except that it provides a [borrowed buffer](https://docs.python.org/3/c-api/arg.html#c-arg-borrowed-buffer). The result is stored into two C variables, the first one a pointer to a C string, the second one its length. The string may contain embedded null bytes. Unicode objects are converted to C strings using 'utf-8' encoding.


> s ([str](https://docs.python.org/3/library/stdtypes.html#str)) [const char *]
> 
>     Convert a Unicode object to a C pointer to a character string. A pointer to an existing string is stored in the character pointer variable whose address you pass. The C string is NUL-terminated. The Python string must not contain embedded null code points; if it does, a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) exception is raised. Unicode objects are converted to C strings using 'utf-8' encoding. If this conversion fails, a [UnicodeError](https://docs.python.org/3/library/exceptions.html#UnicodeError) is raised.

as we are doing `std::string sString = pRef.asString();`I guess this is creating a NULL terminated string and so don't see the real purpose of 's#'.

Last, if we agree on 's' we need to check Memory Leak

**Comment by pipiche38** [comment]
@gizmocuz you might help me, I'm trying to dig into the root cause, to get understanding why it works on 3.9 and not 3.11 and for that it is advisable  to use PyErr_Print(), but when doing it , I get a linkage error.

```
/usr/bin/ld: CMakeFiles/domoticz.dir/hardware/plugins/PluginProtocols.cpp.o: in function `Plugins::CPluginProtocolJSON::JSONtoPython(Json::Value*)':
PluginProtocols.cpp:(.text+0x1678): undefined reference to `PyErr_Print'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/domoticz.dir/build.make:4809: bin/domoticz] Error 1
make[1]: *** [CMakeFiles/Makefile2:384: CMakeFiles/domoticz.dir/all] Error 2
```

**Comment by pipiche38** [comment]
Py_BuildValue("s", sString.c_str()) returns a new reference, not a borrowed reference, not as 's#'

should be better

```
{
    std::string sString = pRef.asString();
    PyObject* pObj = Py_BuildValue("s", sString.c_str());  // new reference
    if (!pObj) {
        _log.Log(LOG_ERROR, "(%s) failed to build Python string object.", __func__);
    } else {
        if (PyList_SetItem(pRetVal, Index++, pObj) == -1) {  // steals reference only on success
            _log.Log(LOG_ERROR, "(%s) failed to add item '%zd' to list for string.", __func__, Index - 1);
            Py_DECREF(pObj);  // clean up because PyList_SetItem failed
        }
    }
}
```

**Comment by Xenomes** [comment]
Thanks for your help! I'll test this with the next beta build once it's available.

**Comment by Xenomes** [comment]
Everything is working perfectly again, just like before! Thanks everyone for your help and support.
