### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2559]
After Updating from 9b171b11 to  27a7bc2d

Here is an extract of the Compilation error when Building domoticz

```
Scanning dependencies of target domoticz
[ 22%] Building CXX object CMakeFiles/domoticz.dir/main/Camera.cpp.o
In file included from /usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:3,
                 from /usr/share/domoticz/beta-domoticz/main/Scheduler.h:4,
                 from /usr/share/domoticz/beta-domoticz/main/mainworker.h:5,
                 from /usr/share/domoticz/beta-domoticz/main/Camera.cpp:7:
/usr/share/domoticz/beta-domoticz/main/../hardware/ColorSwitch.h: In member function ‘void _tColorSwitch::serialize(Archive&)’:
/usr/share/domoticz/beta-domoticz/main/../hardware/ColorSwitch.h:68:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("len", len);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/ColorSwitch.h:69:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("type", type);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/ColorSwitch.h:70:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("subtype", subtype);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/ColorSwitch.h:71:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("id", id);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/ColorSwitch.h:72:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("dunit", dunit);
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:679:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("mins", mins);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:680:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("battery_level", battery_level);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h: In member function ‘void _tEVOHOME3::serialize(Archive&)’:
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:699:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("len", len);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:700:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("type", type);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:701:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("subtype", subtype);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:702:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("id1", id1);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:703:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("id2", id2);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:704:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("id3", id3);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:705:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("devno", devno);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:706:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("demand", demand);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:707:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("updatetype", updatetype);
        ^~~~~~
/usr/share/domoticz/beta-domoticz/main/../hardware/hardwaretypes.h:708:8: error: ‘cereal’ has not been declared
   ar & cereal::make_nvp("battery_level", battery_level);
        ^~~~~~
```

**Comment by gizmocuz** [comment]
Already fixed, please give developers some time (an hour, a day) to find out for themselves, and even worse, working on a fix
