### ISSUE TITLE
Errors building MQTT 

### ISSUE THREAD

**Issue by xriser** [domoticz/domoticz#3732]
`[ 45%] Building CXX object CMakeFiles/domoticz.dir/hardware/MQTT.cpp.o                                                                                                                                           
/tmp/domoticz/hardware/MQTT.cpp: In constructor 'MQTT::MQTT(int, const string&, short unsigned int, const string&, const string&, const string&, int, int)':                                                     
/tmp/domoticz/hardware/MQTT.cpp:33:31: warning: 'mosqpp::mosquittopp::mosquittopp(const char*, bool)' is deprecated [-Wdeprecated-declarations]                                                                  
 mosqpp::mosquittopp("Domoticz")                                                                                                                                                                                 
                               ^                                                                                                                                                                                 
In file included from /tmp/domoticz/hardware/MQTT.h:10,                                                                                                                                                          
                 from /tmp/domoticz/hardware/MQTT.cpp:2:                                                                                                                                                         
/usr/include/mosquittopp.h:94:14: note: declared here                                                                                                                                                            
   DEPRECATED mosquittopp(const char *id=NULL, bool clean_session=true);                                                                                                                                         
              ^~~~~~~~~~~                                                                                                                                                                                        
/tmp/domoticz/hardware/MQTT.cpp:38:10: warning: 'int mosqpp::lib_init()' is deprecated [-Wdeprecated-declarations]                                                                                               
  mosqpp::lib_init();                                                                                                                                                                                            
          ^~~~~~~~                                                                                                                                                                                               
In file included from /tmp/domoticz/hardware/MQTT.h:10,                                                                                                                                                          
                 from /tmp/domoticz/hardware/MQTT.cpp:2:                                                                                                                                                         
/usr/include/mosquittopp.h:48:30: note: declared here                                                                                                                                                            
 mosqpp_EXPORT int DEPRECATED lib_init();                                                                                                                                                                        
                              ^~~~~~~~                                                                                                                                                                           
/tmp/domoticz/hardware/MQTT.cpp:38:19: warning: 'int mosqpp::lib_init()' is deprecated [-Wdeprecated-declarations]                                                                                               
  mosqpp::lib_init();                                                                                                                                                                                            
                   ^                                                                                                                                                                                             
In file included from /tmp/domoticz/hardware/MQTT.h:10,                                                                                                                                                          
                 from /tmp/domoticz/hardware/MQTT.cpp:2:                                                                                                                                                         
/usr/include/mosquittopp.h:48:30: note: declared here                                                                                                                                                            
 mosqpp_EXPORT int DEPRECATED lib_init();                                                                                                                                                                        
                              ^~~~~~~~                                                                                                                                                                           
/tmp/domoticz/hardware/MQTT.cpp:38:19: warning: 'int mosqpp::lib_init()' is deprecated [-Wdeprecated-declarations]                                                                                               
  mosqpp::lib_init();                                                                                                                                                                                            
                   ^                                                                                                                                                                                             
In file included from /tmp/domoticz/hardware/MQTT.h:10,                                                                                                                                                          
                 from /tmp/domoticz/hardware/MQTT.cpp:2:                                                                                                                                                         
/usr/include/mosquittopp.h:48:30: note: declared here                                                                                                                                                            
 mosqpp_EXPORT int DEPRECATED lib_init();                                                                                                                                                                        
                              ^~~~~~~~                                                                                                        `

**Comment by gizmocuz** [comment]
@xriser , these are warnings are not errors, it's an external library.
I will see if i can remove the deprecated 'warning' in a feature build...

**Comment by gizmocuz** [comment]
Seems you are not using the build in domoticz MQTT but you use the headers from your system
Which is fine, but ignore the deprecated warnings
(/usr/include/mosquittopp.h)

**Comment by rkluwen** [comment]
I don't have the mosquitto libraries externally installed. But on two different systems (pi & ubuntu) I got:

[  1%] Building CXX object MQTT/CMakeFiles/mqtt.dir/mosquittopp.cpp.o
/home/pi/domoticz/MQTT/mosquittopp.cpp: In member function ‘void mosqpp::mosquittopp::clear_callbacks()’:
/home/pi/domoticz/MQTT/mosquittopp.cpp:215:41: error: ‘nullptr’ was not declared in this scope
  mosquitto_connect_callback_set(m_mosq, nullptr);
                                         ^
MQTT/CMakeFiles/mqtt.dir/build.make:62: recipe for target 'MQTT/CMakeFiles/mqtt.dir/mosquittopp.cpp.o' failed
make[2]: *** [MQTT/CMakeFiles/mqtt.dir/mosquittopp.cpp.o] Error 1
CMakeFiles/Makefile2:256: recipe for target 'MQTT/CMakeFiles/mqtt.dir/all' failed
make[1]: *** [MQTT/CMakeFiles/mqtt.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rkluwen** [comment]
At the same time, after a quick manual patch to mosquittopp.cpp, when linking, I got:

MQTT/libmqtt.a(net_mosq.c.o): In function `net__init_ssl_ctx':
net_mosq.c:(.text+0xbac): undefined reference to `SSL_CTX_set_alpn_protos'

**Comment by gizmocuz** [comment]
@rkluwen , you have to link against openssl 1.1.x
nullptr not found ?

**Comment by svde** [comment]
Mine also isn't building anymore (4.11488 was the last one that built).

Buildlog:
https://build.opensuse.org/build/home:stefan_van_der_eijk/Fedora_31/x86_64/domoticz/_log

using external mosquitto-devel-1.6.7-1.fc31

**Comment by gizmocuz** [comment]
@svde , could you try with the build in ? We are also using 1.6.7

**Comment by svde** [comment]
It compiles with the built-in one. Still a but puzzled why it doesn't take the system one...

**Comment by xbeaudouin** [comment]
Same issue on my FreeBSD. I didn't such issue before the addition of "internal" mosquitto... 
Will try to find why, for now here is some log :

`===>  Building for domoticz-devel-4.11499
[1/212] /usr/bin/c++  -DENABLE_PYTHON -DHAVE_EXECINFO_H -DWITH_EXTERNAL_LUA -DWITH_EXTERNAL_SQLITE -DWITH_LIBUSB -DWITH_OPENZWAVE -DWITH_TLS -DWWW_ENABLE_SSL -I/usr/local/include/lua53 -I/usr/local/include/python3.6m -I/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/main -I/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/tinyxpath -I/usr/local/include/minizip -I/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/hardware/openzwave -isystem /usr/local/include -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -DLIBICONV_PLUG -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -DLIBICONV_PLUG   -pthread -std=gnu++11 -MD -MT CMakeFiles/domoticz.dir/hardware/ZiBlueSerial.cpp.o -MF CMakeFiles/domoticz.dir/hardware/ZiBlueSerial.cpp.o.d -o CMakeFiles/domoticz.dir/hardware/ZiBlueSerial.cpp.o -c /usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/hardware/ZiBlueSerial.cpp
[2/212] /usr/bin/c++  -DENABLE_PYTHON -DHAVE_EXECINFO_H -DWITH_EXTERNAL_LUA -DWITH_EXTERNAL_SQLITE -DWITH_LIBUSB -DWITH_OPENZWAVE -DWITH_TLS -DWWW_ENABLE_SSL -I/usr/local/include/lua53 -I/usr/local/include/python3.6m -I/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/main -I/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/tinyxpath -I/usr/local/include/minizip -I/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/hardware/openzwave -isystem /usr/local/include -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -DLIBICONV_PLUG -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -DLIBICONV_PLUG   -pthread -std=gnu++11 -MD -MT CMakeFiles/domoticz.dir/hardware/TTNMQTT.cpp.o -MF CMakeFiles/domoticz.dir/hardware/TTNMQTT.cpp.o.d -o CMakeFiles/domoticz.dir/hardware/TTNMQTT.cpp.o -c /usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/hardware/TTNMQTT.cpp
FAILED: CMakeFiles/domoticz.dir/hardware/TTNMQTT.cpp.o 
/usr/bin/c++  -DENABLE_PYTHON -DHAVE_EXECINFO_H -DWITH_EXTERNAL_LUA -DWITH_EXTERNAL_SQLITE -DWITH_LIBUSB -DWITH_OPENZWAVE -DWITH_TLS -DWWW_ENABLE_SSL -I/usr/local/include/lua53 -I/usr/local/include/python3.6m -I/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/main -I/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/tinyxpath -I/usr/local/include/minizip -I/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/hardware/openzwave -isystem /usr/local/include -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -DLIBICONV_PLUG -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -DLIBICONV_PLUG   -pthread -std=gnu++11 -MD -MT CMakeFiles/domoticz.dir/hardware/TTNMQTT.cpp.o -MF CMakeFiles/domoticz.dir/hardware/TTNMQTT.cpp.o.d -o CMakeFiles/domoticz.dir/hardware/TTNMQTT.cpp.o -c /usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/hardware/TTNMQTT.cpp
In file included from /usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/hardware/TTNMQTT.cpp:2:
/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/hardware/TTNMQTT.h:20:48: warning: 'mosquittopp' is deprecated [-Wdeprecated-declarations]
class CTTNMQTT : public MySensorsBase, mosqpp::mosquittopp
                                               ^
/usr/local/include/mosquittopp.h:90:21: note: 'mosquittopp' has been explicitly marked deprecated here
class mosqpp_EXPORT DEPRECATED mosquittopp {
                    ^
/usr/local/include/mosquittopp.h:31:38: note: expanded from macro 'DEPRECATED'
#  define DEPRECATED __attribute__ ((deprecated))
                                     ^
/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/hardware/TTNMQTT.cpp:55:2: warning: 'mosquittopp' is deprecated [-Wdeprecated-declarations]
        mosquittopp(CLIENTID),
        ^
/usr/local/include/mosquittopp.h:94:3: note: 'mosquittopp' has been explicitly marked deprecated here
                DEPRECATED mosquittopp(const char *id=NULL, bool clean_session=true);
                ^
/usr/local/include/mosquittopp.h:31:38: note: expanded from macro 'DEPRECATED'
#  define DEPRECATED __attribute__ ((deprecated))
                                     ^
/usr/home/kiwi/git/freebsd-ports/www/domoticz-devel/work/domoticz-c8ee757ce/hardware/TTNMQTT.cpp:77:10: warning: 'lib_init' is deprecated [-Wdeprecated-declarations]
`

The most interressing stuff is : 
/usr/local/include/mosquittopp.h:90:21: note: 'mosquittopp' has been explicitly marked deprecated here

**Comment by gizmocuz** [comment]
Thanks for the feedback. SSL_CTX_set_alpn_protos is an OpenSSL function, make sure you link against 1.1.x
Make clean the build folder... delete the CMakeCache file/folder, or even better, checkout a fresh copy of Domoticz

**Comment by rkluwen** [comment]
Upgrading mosquitto sources is one thing.
Upgrading an entire openssl version, which isn't in the public repository is a far shot for me.

**Comment by gizmocuz** [comment]
@rkluwen , I do not know what distribution you use, but 1.1.x is pretty standard these days ?

https://launchpad.net/ubuntu/bionic/+source/openssl

**Comment by rkluwen** [comment]
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"

**Comment by gizmocuz** [comment]
@rkluwen , that is a bit outdated! Very outdated, you are running two distributions behind.

There are guides online to upgrade to buster.

But if it is only Domoticz running on it, then i would backup the domoticz folder and install a clean buster image

**Comment by waltervl** [comment]
This issue can be closed?
