### ISSUE TITLE
Latest source does not compile with latest boost version: 1.59.0

### ISSUE THREAD

**Issue by nesalkiN** [domoticz/domoticz#29]
Building C object lua/src/CMakeFiles/lua.dir/lcode.c.o
In file included from /usr/local/include/boost/thread.hpp:24:0,
                 from /home/pi/dev-domoticz/main/stdafx.h:58:
/usr/local/include/boost/thread/future.hpp:2043:37: error: ‘is_copy_constructible’ was not declared in this scope
/usr/local/include/boost/thread/future.hpp:2043:37: note: suggested alternative:
/usr/local/include/boost/move/detail/type_traits.hpp:742:8: note:   ‘boost::move_detail::is_copy_constructible’
/usr/local/include/boost/thread/future.hpp:2043:61: error: template argument 1 is invalid
/usr/local/include/boost/thread/future.hpp:2043:62: error: expected identifier before ‘::’ token
/usr/local/include/boost/thread/future.hpp:2043:70: error: expected initializer before ‘&&’ token
In file included from /usr/local/include/boost/thread.hpp:24:0,
                 from /home/pi/dev-domoticz/main/stdafx.h:58:
/usr/local/include/boost/thread/future.hpp:2098:37: error: ‘is_copy_constructible’ was not declared in this scope
/usr/local/include/boost/thread/future.hpp:2098:37: note: suggested alternative:
/usr/local/include/boost/move/detail/type_traits.hpp:742:8: note:   ‘boost::move_detail::is_copy_constructible’
/usr/local/include/boost/thread/future.hpp:2098:61: error: template argument 1 is invalid
/usr/local/include/boost/thread/future.hpp:2098:62: error: expected identifier before ‘::’ token
/usr/local/include/boost/thread/future.hpp:2098:70: error: expected initializer before ‘&&’ token
[ 19%] Building C object lua/src/CMakeFiles/lua.dir/lctype.c.o
[ 20%] Building C object lua/src/CMakeFiles/lua.dir/ldebug.c.o
[ 20%] Building C object lua/src/CMakeFiles/lua.dir/ldo.c.o
[ 21%] Building C object lua/src/CMakeFiles/lua.dir/ldump.c.o
[ 21%] Building C object lua/src/CMakeFiles/lua.dir/lfunc.c.o
[ 22%] Building C object lua/src/CMakeFiles/lua.dir/lgc.c.o
[ 22%] Building C object lua/src/CMakeFiles/lua.dir/llex.c.o
[ 23%] Building C object lua/src/CMakeFiles/lua.dir/lmem.c.o
[ 24%] Building C object lua/src/CMakeFiles/lua.dir/lobject.c.o
[ 24%] Building C object lua/src/CMakeFiles/lua.dir/lopcodes.c.o
[ 25%] Building C object lua/src/CMakeFiles/lua.dir/lparser.c.o
[ 25%] Building C object lua/src/CMakeFiles/lua.dir/lstate.c.o
[ 26%] CMakeFiles/domoticz_gch.dir/build.make:51: receptet för målet ”stdafx.h.gch/.c++” misslyckades
make[2]: **\* [stdafx.h.gch/.c++] Fel 1
CMakeFiles/Makefile2:99: receptet för målet ”CMakeFiles/domoticz_gch.dir/all” misslyckades
make[1]: **\* [CMakeFiles/domoticz_gch.dir/all] Fel 2
make[1]: **\* Inväntar oavslutade jobb...

**Comment by gizmocuz** [comment]
At the moment we are building against 1.58, but please provide a patch.... (against 1.59)

**Comment by nesalkiN** [comment]
If i could I would of course. The Wiki says "Its recommended that you use the latest boost libraries - as of 15th April 2015 that is version 1.58.0 For this we need to compile/install them by issuing the following commands" so I did go by that and downloded the latest boost libraries instead. I will revert to 1.58.0. Thanks.

**Comment by gizmocuz** [comment]
Okey, good the wiki shows how to do it.
At the moment am building 1.59, and see if i could find some problems

**Comment by gizmocuz** [comment]
I followed the same wiki, and replaced 1.58 with 1.59, and have no issues, please check?
I updated the wiki for 1.59

**Comment by nesalkiN** [comment]
Strange. I don't know what to check. I started from 0 and checked out the latest source and it gives me the errors in the op. Hmm. I'll check again.

**Comment by gizmocuz** [comment]
try building boost 1.59, like in the wiki,
then issue in the domoticz build folder
cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt

I removed all cmake cache files, but in your case, starting from scratch that wont be needed

i think building/installing the 1.59 like in the wiki should be ok

**Comment by nesalkiN** [comment]
This is what I get, Pi 2:

pi@Pi2Domo ~ $ LANG=C git clone https://github.com/domoticz/domoticz.git dev-domoticz
Cloning into 'dev-domoticz'...
remote: Counting objects: 13925, done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 13925 (delta 42), reused 0 (delta 0), pack-reused 13820
Receiving objects: 100% (13925/13925), 111.19 MiB | 2.41 MiB/s, done.
Resolving deltas: 100% (9043/9043), done.
Checking out files: 100% (1572/1572), done.
pi@Pi2Domo ~ $ cd dev-domoticz
pi@Pi2Domo ~/dev-domoticz $ LANG=C cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
-- The C compiler identification is GNU 4.6.3
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Failed to find openssl include files (ssl.h), no TLS support
-- Failed to find the openssl library, no TLS support
-- The CXX compiler identification is GNU 4.6.3
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Compiling Revision #2866
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
-- Linking against boost static libraries
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.7")
-- ZLIB libraries found at: /usr/lib/arm-linux-gnueabihf/libz.so
-- ZLIB includes found at: /usr/include
-- Found CURL: /usr/lib/arm-linux-gnueabihf/libcurl.so (found version "7.26.0")
-- Curl libraries found at: /usr/lib/arm-linux-gnueabihf/libcurl.so
-- Curl includes found at: /usr/include
-- Found LIBUSB: /usr/lib/arm-linux-gnueabihf/libusb.so
-- LIBUSB found at: /usr/lib/arm-linux-gnueabihf/libusb.so
-- Crypto library found at: /usr/lib/arm-linux-gnueabihf/libcrypto.so
-- /home/pi/open-zwave-read-only/libopenzwave.a
-- /usr/lib/libudev.a
-- Building on Raspberry Pi... (bcm_host.h found in /opt/vc/include)
-- ==== WiringPi include file (wiringPi.h) not found. GPIO support disabled.
-- ==== (Please follow http://wiringpi.com/download-and-install/ if you want to use GPIO.)
/usr/bin/c++ -DPCHCOMPILE -O3;-DNDEBUG;-I/home/pi/dev-domoticz/main;-I/usr/include;-I/usr/include;-I/home/pi/dev-domoticz/hardware/openzwave;;-DNS_ENABLE_SSL;-DWITH_LIBUSB;-DNS_ENABLE_SSL;-DWITH_OPENZWAVE -x c++-header -o /home/pi/dev-domoticz/stdafx.h.gch/.c++ /home/pi/dev-domoticz/main/stdafx.h
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/dev-domoticz
pi@Pi2Domo ~/dev-domoticz $ LANG=C make -j 4
Scanning dependencies of target revisiontag
Scanning dependencies of target sqlite
Scanning dependencies of target mqtt
Scanning dependencies of target lua
-- Found Git: /usr/bin/git (found version "1.7.10.4")
[  0%] Building C object MQTT/CMakeFiles/mqtt.dir/mosquitto.c.o
[  0%] [  0%] Built target revisiontag
Building C object lua/src/CMakeFiles/lua.dir/lauxlib.c.o
Scanning dependencies of target domoticz_gch
[  1%] Generating stdafx.h.gch/.c++
[  2%] Building C object sqlite/CMakeFiles/sqlite.dir/sqlite3.c.o
[  3%] Building C object MQTT/CMakeFiles/mqtt.dir/logging_mosq.c.o
[  4%] Building C object lua/src/CMakeFiles/lua.dir/lbaselib.c.o
[  4%] Building C object MQTT/CMakeFiles/mqtt.dir/memory_mosq.c.o
[  5%] Building C object MQTT/CMakeFiles/mqtt.dir/messages_mosq.c.o
[  6%] [  6%] Building C object lua/src/CMakeFiles/lua.dir/lbitlib.c.o
Building C object MQTT/CMakeFiles/mqtt.dir/net_mosq.c.o
[  6%] Building C object lua/src/CMakeFiles/lua.dir/lcorolib.c.o
[  7%] [  8%] Building C object MQTT/CMakeFiles/mqtt.dir/read_handle.c.o
Building C object lua/src/CMakeFiles/lua.dir/ldblib.c.o
[  8%] Building C object MQTT/CMakeFiles/mqtt.dir/read_handle_client.c.o
[  9%] Building C object MQTT/CMakeFiles/mqtt.dir/read_handle_shared.c.o
[ 10%] Building C object MQTT/CMakeFiles/mqtt.dir/send_client_mosq.c.o
[ 10%] Building C object lua/src/CMakeFiles/lua.dir/liolib.c.o
[ 10%] Building C object MQTT/CMakeFiles/mqtt.dir/send_mosq.c.o
[ 11%] Building C object MQTT/CMakeFiles/mqtt.dir/socks_mosq.c.o
[ 11%] Building C object MQTT/CMakeFiles/mqtt.dir/srv_mosq.c.o
[ 12%] Building C object MQTT/CMakeFiles/mqtt.dir/thread_mosq.c.o
[ 13%] Building C object lua/src/CMakeFiles/lua.dir/lmathlib.c.o
[ 13%] Building C object MQTT/CMakeFiles/mqtt.dir/time_mosq.c.o
[ 14%] Building C object MQTT/CMakeFiles/mqtt.dir/tls_mosq.c.o
[ 14%] Building C object MQTT/CMakeFiles/mqtt.dir/util_mosq.c.o
[ 14%] Building C object lua/src/CMakeFiles/lua.dir/loslib.c.o
[ 15%] Building C object MQTT/CMakeFiles/mqtt.dir/will_mosq.c.o
Linking C static library libmqtt.a
[ 16%] [ 16%] Building C object lua/src/CMakeFiles/lua.dir/lstrlib.c.o
Built target mqtt
[ 16%] Building C object lua/src/CMakeFiles/lua.dir/ltablib.c.o
[ 17%] Building C object lua/src/CMakeFiles/lua.dir/loadlib.c.o
In file included from /usr/local/include/boost/thread.hpp:24:0,
                 from /home/pi/dev-domoticz/main/stdafx.h:58:
/usr/local/include/boost/thread/future.hpp:2043:37: error: 'is_copy_constructible' was not declared in this scope
/usr/local/include/boost/thread/future.hpp:2043:37: note: suggested alternative:
/usr/local/include/boost/move/detail/type_traits.hpp:742:8: note:   'boost::move_detail::is_copy_constructible'
/usr/local/include/boost/thread/future.hpp:2043:61: error: template argument 1 is invalid
/usr/local/include/boost/thread/future.hpp:2043:62: error: expected identifier before '::' token
/usr/local/include/boost/thread/future.hpp:2043:70: error: expected initializer before '&&' token
In file included from /usr/local/include/boost/thread.hpp:24:0,
                 from /home/pi/dev-domoticz/main/stdafx.h:58:
/usr/local/include/boost/thread/future.hpp:2098:37: error: 'is_copy_constructible' was not declared in this scope
/usr/local/include/boost/thread/future.hpp:2098:37: note: suggested alternative:
/usr/local/include/boost/move/detail/type_traits.hpp:742:8: note:   'boost::move_detail::is_copy_constructible'
/usr/local/include/boost/thread/future.hpp:2098:61: error: template argument 1 is invalid
/usr/local/include/boost/thread/future.hpp:2098:62: error: expected identifier before '::' token
/usr/local/include/boost/thread/future.hpp:2098:70: error: expected initializer before '&&' token
[ 18%] Building C object lua/src/CMakeFiles/lua.dir/linit.c.o
[ 18%] Building C object lua/src/CMakeFiles/lua.dir/lapi.c.o
[ 19%] Building C object lua/src/CMakeFiles/lua.dir/lcode.c.o
[ 19%] Building C object lua/src/CMakeFiles/lua.dir/lctype.c.o
[ 20%] Building C object lua/src/CMakeFiles/lua.dir/ldebug.c.o
[ 20%] Building C object lua/src/CMakeFiles/lua.dir/ldo.c.o
[ 21%] Building C object lua/src/CMakeFiles/lua.dir/ldump.c.o
[ 21%] Building C object lua/src/CMakeFiles/lua.dir/lfunc.c.o
[ 22%] Building C object lua/src/CMakeFiles/lua.dir/lgc.c.o
[ 22%] Building C object lua/src/CMakeFiles/lua.dir/llex.c.o
CMakeFiles/domoticz_gch.dir/build.make:51: recipe for target 'stdafx.h.gch/.c++' failed
make[2]: **\* [stdafx.h.gch/.c++] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/domoticz_gch.dir/all' failed
make[1]: **\* [CMakeFiles/domoticz_gch.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[ 23%] Building C object lua/src/CMakeFiles/lua.dir/lmem.c.o
[ 24%] Building C object lua/src/CMakeFiles/lua.dir/lobject.c.o
[ 24%] Building C object lua/src/CMakeFiles/lua.dir/lopcodes.c.o
[ 25%] [ 25%] Building C object lua/src/CMakeFiles/lua.dir/lparser.c.o
Building C object lua/src/CMakeFiles/lua.dir/lstate.c.o
[ 26%] Building C object lua/src/CMakeFiles/lua.dir/lstring.c.o
[ 26%] Building C object lua/src/CMakeFiles/lua.dir/ltable.c.o
[ 27%] Building C object lua/src/CMakeFiles/lua.dir/ltm.c.o
[ 27%] Building C object lua/src/CMakeFiles/lua.dir/lundump.c.o
[ 28%] [ 29%] Building C object lua/src/CMakeFiles/lua.dir/lvm.c.o
Building C object lua/src/CMakeFiles/lua.dir/lzio.c.o
Linking C static library liblua.a
[ 29%] Built target lua
Linking C static library libsqlite.a
[ 29%] Built target sqlite
Makefile:133: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by nesalkiN** [comment]
Manually removed boost and installed 1.57.0 as the guide said before and it worked. Could try the same for 1.59

--with-python for the last boost install-step seems to have been removed in a current edit of the wiki page?

**Comment by gizmocuz** [comment]
the guide said 1.58.
booth-python was not used, so i removed it, saves compile/install time

**Comment by nesalkiN** [comment]
It said that 1.58 was the latest but in the code section it was 57 ;)

**Comment by gizmocuz** [comment]
Maybe there are two different wiki pages ?
I followed:
http://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

(this also applies for other linux systems), here it was 1.58, and i changed it to 1.59
Is it working when you follow this guide, and 1.59 ?

**Comment by nesalkiN** [comment]
It's workin now with 1.59. Did some manual cleanup
