### ISSUE TITLE
Build failure with python 3.8

### ISSUE THREAD

**Issue by ffontaine** [domoticz/domoticz#3703]
domoticz fails to build with python 3.8 with the following output
```
[100%] Linking CXX executable domoticz
/home/rclinux/rc-buildroot-test/scripts/instance-0/output/host/opt/ext-toolchain/bin/../lib/gcc/arc-buildroot-linux-uclibc/8.2.1/../../../../arc-buildroot-linux-uclibc/bin/ld: CMakeFiles/domoticz.dir/main/EventsPythonModule.cpp.o: in function `_Py_DECREF.isra.12':
EventsPythonModule.cpp:(.text+0x52): undefined reference to `_Py_Dealloc'
/home/rclinux/rc-buildroot-test/scripts/instance-0/output/host/opt/ext-toolchain/bin/../lib/gcc/arc-buildroot-linux-uclibc/8.2.1/../../../../arc-buildroot-linux-uclibc/bin/ld: EventsPythonModule.cpp:(.text+0x52): undefined reference to `_Py_Dealloc'
/home/rclinux/rc-buildroot-test/scripts/instance-0/output/host/opt/ext-toolchain/bin/../lib/gcc/arc-buildroot-linux-uclibc/8.2.1/../../../../arc-buildroot-linux-uclibc/bin/ld: CMakeFiles/domoticz.dir/hardware/plugins/Plugins.cpp.o: in function `_Py_DECREF.isra.21':
Plugins.cpp:(.text+0x96): undefined reference to `_Py_Dealloc'
/home/rclinux/rc-buildroot-test/scripts/instance-0/output/host/opt/ext-toolchain/bin/../lib/gcc/arc-buildroot-linux-uclibc/8.2.1/../../../../arc-buildroot-linux-uclibc/bin/ld: Plugins.cpp:(.text+0x96): undefined reference to `_Py_Dealloc'
/home/rclinux/rc-buildroot-test/scripts/instance-0/output/host/opt/ext-toolchain/bin/../lib/gcc/arc-buildroot-linux-uclibc/8.2.1/../../../../arc-buildroot-linux-uclibc/bin/ld: CMakeFiles/domoticz.dir/hardware/plugins/PluginProtocols.cpp.o: in function `_Py_DECREF.isra.11':
PluginProtocols.cpp:(.text+0x16): undefined reference to `_Py_Dealloc'
/home/rclinux/rc-buildroot-test/scripts/instance-0/output/host/opt/ext-toolchain/bin/../lib/gcc/arc-buildroot-linux-uclibc/8.2.1/../../../../arc-buildroot-linux-uclibc/bin/ld: CMakeFiles/domoticz.dir/hardware/plugins/PluginProtocols.cpp.o:PluginProtocols.cpp:(.text+0x16): more undefined references to `_Py_Dealloc' follow
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:3635: recipe for target 'domoticz' failed
make[3]: *** [domoticz] Error 1
```
From my understanding, this is related to the following change in python 3.8 (https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build):

> On Unix, C extensions are no longer linked to libpython except on Android and Cygwin. It is now possible for a statically linked Python to load a C extension built using a shared library Python. (Contributed by Victor Stinner in bpo-21536.)
> 
> On Unix, when Python is built in debug mode, import now also looks for C extensions compiled in release mode and for C extensions compiled with the stable ABI. (Contributed by Victor Stinner in bpo-36722.)
> 
> To embed Python into an application, a new --embed option must be passed to python3-config --libs --embed to get -lpython3.8 (link the application to libpython). To support both 3.8 and older, try python3-config --libs --embed first and fallback to python3-config --libs (without --embed) if the previous command fails.
> 
> Add a pkg-config python-3.8-embed module to embed Python into an application: pkg-config python-3.8-embed --libs includes -lpython3.8. To support both 3.8 and older, try pkg-config python-X.Y-embed --libs first and fallback to pkg-config python-X.Y --libs (without --embed) if the previous command fails (replace X.Y with the Python version).
> 
> On the other hand, pkg-config python3.8 --libs no longer contains -lpython3.8. C extensions must not be linked to libpython (except on Android and Cygwin, whose cases are handled by the script); this change is backward incompatible on purpose. (Contributed by Victor Stinner in bpo-36721.)

I don't know how to fix it, so I'm seeking your advice.

**Comment by kofec** [comment]
I see the same:
`
[ 14%] Linking CXX executable domoticz
/mnt/openwrt/OpenwrtATH79/staging_dir/toolchain-mips_24kc_gcc-8.3.0_musl/lib/gcc/mips-openwrt-linux-musl/8.3.0/../../../../mips-openwrt-linux-musl/bin/ld: /mnt/openwrt/OpenwrtATH79/tmp/cc9IMpCM.ltrans6.ltrans.o: in function `_Py_DECREF.isra.14':
<artificial>:(.text+0x1bb8): undefined reference to `_Py_Dealloc'
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:3656: recipe for target 'domoticz' failed
make[5]: *** [domoticz] Error 1
make[5]: Leaving directory '/mnt/openwrt/OpenwrtATH79/build_dir/target-mips_24kc_musl/domoticz-757ce059277883acd648774ae23889cbb5f88f6d'
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory '/mnt/openwrt/OpenwrtATH79/build_dir/target-mips_24kc_musl/domoticz-757ce059277883acd648774ae23889cbb5f88f6d'
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/mnt/openwrt/OpenwrtATH79/build_dir/target-mips_24kc_musl/domoticz-757ce059277883acd648774ae23889cbb5f88f6d'
Makefile:139: recipe for target '/mnt/openwrt/OpenwrtATH79/build_dir/target-mips_24kc_musl/domoticz-757ce059277883acd648774ae23889cbb5f88f6d/.built' failed
make[2]: *** [/mnt/openwrt/OpenwrtATH79/build_dir/target-mips_24kc_musl/domoticz-757ce059277883acd648774ae23889cbb5f88f6d/.built] Error 2
make[2]: Leaving directory '/mnt/openwrt/OpenwrtATH79/feeds/packages/utils/domoticz'
time: package/feeds/packages/domoticz/compile#125.60#3.93#127.69
package/Makefile:111: recipe for target 'package/feeds/packages/domoticz/compile' failed
make[1]: *** [package/feeds/packages/domoticz/compile] Error 2
make[1]: Leaving directory '/mnt/openwrt/OpenwrtATH79'
/mnt/openwrt/OpenwrtATH79/include/toplevel.mk:225: recipe for target 'package/domoticz/compile' failed
make: *** [package/domoticz/compile] Error 2`

**Comment by ffontaine** [comment]
domoticz is not the only package to be affected by this breaking change in python 3.8. Some packages have redefined their own py3__Py_DECREF() function (see https://github.com/vim/vim/issues/4080), while other are retrieving the missing python library through the --embed option (https://developer.pidgin.im/ticket/17396). I don't know what is the correct solution as I'm far from being a python expert.

**Comment by gizmocuz** [comment]
Maybe this is something that @dnpwwo could have a look at ?

**Comment by dnpwwo** [comment]
I read the release note and (as always) its pretty incomprehensible if you aren't a part of the Python dev team.  Also not sure we have the same problem though.  

(The 'vim' link was interesting, that is the first project that supports late linking that I've seen)

I'm suspicious they have just changed the dealloc function in 3.8.  Domoticz already has 'magic' handling for it in DelayedLink.h:

```
 #ifdef _DEBUG
      // In a debug build dealloc is a function but for release builds its a macro
      DECLARE_PYTHON_SYMBOL(void, _Py_Dealloc, PyObject*); 
 #endif
```
Looks to me like they have made it always a macro or always a function.

Are you guys build Release or Debug images?

**Comment by ffontaine** [comment]
Buildroot autobuilders build domoticz in both versions: Debug and Release and indeed it seems that we have build failures only in Release mode. I'll double check it.

**Comment by kofec** [comment]
I'm building in release mode
DCMAKE_BUILD_TYPE=Release

**Comment by ffontaine** [comment]
The error is not related to dealloc function being a macro or function. I tried to change

 ```
#ifdef _DEBUG
      // In a debug build dealloc is a function but for release builds its a macro
      DECLARE_PYTHON_SYMBOL(void, _Py_Dealloc, PyObject*); 
 #endif
```
to 
```
 #ifdef defined(_DEBUG) || PY_VERSION_HEX >= 0x030800f0
      // In a debug build or with python >= 3.8 dealloc is a function otherwise its a macro
      DECLARE_PYTHON_SYMBOL(void, _Py_Dealloc, PyObject*); 
 #endif
```
But this did not work.

Copy/pasting vim solution in DelayedLink fixes the linking error (see https://github.com/ffontaine/domoticz/commit/e9bd383ceb63db7cfe8a284014f0cdf8c2bfe4f0) however I'm not able to run-time test it.

**Comment by kofec** [comment]
@ffontaine - thanks. I use your propose patch and domoticz compile fine and is working. I don't test any python plugin yet.

```

2019-11-06 16:53:26.213 Status: Domoticz V4.11468 (c)2012-2019 GizMoCuz
2019-11-06 16:53:26.213 Status: Build Hash: 508cc66a, Date: 2019-11-05 16:05:44
2019-11-06 16:53:26.213 Status: Startup Path: /usr/share/domoticz/
2019-11-06 16:53:26.772 Status: PluginSystem: Started, Python version '3.8.0'.
2019-11-06 16:53:26.798 Status: WebServer(HTTP) started on address: :: with port 8080
2019-11-06 16:53:26.807 Status: RxQueue: queue worker started...
2019-11-06 16:53:26.807 Status: TCPServer: shared server started...
2019-11-06 16:53:28.813 Status: Hardware Monitor: Started
2019-11-06 16:53:28.822 Status: EventSystem: reset all events...
2019-11-06 16:53:28.824 Status: EventSystem: reset all device statuses...
2019-11-06 16:53:28.869 Status: PluginSystem: Entering work loop.
2019-11-06 16:53:29.060 Status: Python EventSystem: Initalizing event module.
2019-11-06 16:53:29.062 Status: EventSystem: Queue thread started...
2019-11-06 16:53:29.062 Status: EventSystem: Started

```

**Comment by dnpwwo** [comment]
I suspect this is a braking change for us.  The current minimum Python version is 3.4 but at some stage that may need to change to 3.8.  Obviously its a little early for that given 3.8 hasn't been out that long.

Has anyone tried running a version of Domoticz that was linked against an earlier version of Python against 3.8?

**Comment by ffontaine** [comment]
The suggested fix is enabled only with python 3.8 thanks to PY_VERSION_HEX >= 0x030800f0 so it should not change anything for users using older python versions. I sent an official PR. It will be easier to review.
