### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by aldodemi** [domoticz/domoticz#4212]
Comiple error on Ubuntu 20.04 - Domoticz 2020.2.12125
-- Found Git: /usr/bin/git (found version "2.25.1")
-- domoticz has been modified locally: adding "-modified" to hash
[  0%] Built target revisiontag
[  1%] Built target minizip
[  2%] Built target jsoncpp_lib
[ 17%] Built target libmosquitto_static
[ 17%] Built target SQLite3
[ 18%] Building CXX object CMakeFiles/domoticz.dir/main/mainworker.cpp.o
In file included from /home/domoticz/domoticz/main/../hardware/OpenZWave.h:10,
                 from /home/domoticz/domoticz/main/mainworker.cpp:39:
/home/domoticz/domoticz/main/../hardware/openzwave/control_panel/ozwcp.h:41:10: fatal error: Driver.h: No such file or directory
   41 | #include <Driver.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/domoticz.dir/build.make:369: CMakeFiles/domoticz.dir/main/mainworker.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:373: CMakeFiles/domoticz.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
Aldo

**Comment by rwaaren** [comment]
Can you try to start over? So remove directory. clone, cmake and  make?
That worked for me on Debian buster when I hit the same problem.

**Comment by gizmocuz** [comment]
Same issue here, caused by PR #4206
Hope to find time to fix/revert this soon

**Comment by gizmocuz** [comment]
@aldodemi , could you cleanup your build folder (CMake) by removing the following:
CMakeCache.txt
the folder CMakeFiles

Then issue

cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt

and after that issue make/make -j4
