### ISSUE TITLE
Fails to build with Boost 1.70 (Beta1)

### ISSUE THREAD

**Issue by jbeich** [domoticz/domoticz#3117]
Regressed by boostorg/asio@a72fbb0b867f:
```c++
hardware/Pinger.cpp:79:16: error: no member named 'get_io_service' in
      'boost::asio::ip::basic_resolver<boost::asio::ip::icmp, boost::asio::executor>'
                                        resolver_.get_io_service().stop();
                                        ~~~~~~~~~ ^
hardware/Pinger.cpp:121:14: error: no member named 'get_io_service' in
      'boost::asio::ip::basic_resolver<boost::asio::ip::icmp, boost::asio::executor>'
                        resolver_.get_io_service().stop();
                        ~~~~~~~~~ ^
2 errors generated.
```

**Comment by xbeaudouin** [comment]
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236604.
FreeBSD is going to add boost 1.70, so.... Maybe this should be a good idea to find a way to fix that?

**Comment by gizmocuz** [comment]
Could you check with the latest code ?
