### ISSUE TITLE
Compile error after upgrade Ubuntu form 19.10 to 20.04

### ISSUE THREAD

**Issue by aldodemi** [domoticz/domoticz#4170]
Domoticz installed from source, after upgrade Ubuntu form 19.10 to 20.04, found this compile error:
[ 63%] Building CXX object CMakeFiles/domoticz.dir/hardware/PanasonicTV.cpp.o
[ 63%] Building CXX object CMakeFiles/domoticz.dir/hardware/P1MeterBase.cpp.o
/home/domoticz/domoticz/hardware/P1MeterBase.cpp:8:10: fatal error: cryptopp/aes.h: File o directory non esistente
    8 | #include <cryptopp/aes.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/domoticz.dir/build.make:2104: CMakeFiles/domoticz.dir/hardware/P1MeterBase.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:353: CMakeFiles/domoticz.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

Someone can help?
Thank in advance
Aldo

**Comment by Ashitaka57** [comment]
The last commit on P1MeterBase is responsible of that,

I've got the same compile error while building on my QNAP
`[ 43%] Building CXX object CMakeFiles/domoticz.dir/hardware/P1MeterBase.cpp.o
/share/CACHEDEV1_DATA/.qpkg/domoticz_srv/dev-domoticz/hardware/P1MeterBase.cpp:8:10: fatal error: cryptopp/aes.h: No such file or directory
 #include <cryptopp/aes.h>
          ^~~~~~~~~~~~~~~~`

**Comment by gizmocuz** [comment]
We know... and working on it...

**Comment by gizmocuz** [comment]
Should be solved now....

**Comment by Ashitaka57** [comment]
Thanks @gizmocuz, it compiled smoothly ! Thanks for the fast work !
